SELECT
    DISTINCT C.CAR_ID            -- 자동자 ID
    , C.CAR_TYPE                 -- 자동자 종류
    , C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100) AS FEE -- 대여 금액
  FROM CAR_RENTAL_COMPANY_CAR C
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON P.CAR_TYPE = C.CAR_TYPE
   AND P.DURATION_TYPE = '30일 이상'
 WHERE 1=1
   AND C.CAR_TYPE IN ('세단', 'SUV')
   AND C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
   AND C.CAR_ID NOT IN (    /* NOT IN 조건으로 대여할 수 없는 CAR 필터링 */
       SELECT
           DISTINCT CAR_ID
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221131' 
                AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101')
   )    /* 2022년 11월 1일부터 2022년 11월 30일까지 대여할 수 없는 CAR */
 ORDER
    BY C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100) DESC, C.CAR_TYPE, C.CAR_ID DESC