SELECT 
  A.CAR_ID,
  A.CAR_TYPE,
  FLOOR(A.DAILY_FEE * (1 - C.DISCOUNT_RATE / 100) * 30) AS FEE
FROM 
  CAR_RENTAL_COMPANY_CAR A
JOIN 
  CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
WHERE 
  A.CAR_TYPE IN ('세단', 'SUV')
  AND C.DURATION_TYPE = '30일 이상'
  AND A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
      (TO_DATE('2022-11-01', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE)
      OR (TO_DATE('2022-11-30', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE)
      OR (START_DATE BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD') AND TO_DATE('2022-11-30', 'YYYY-MM-DD'))
      OR (END_DATE BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD') AND TO_DATE('2022-11-30', 'YYYY-MM-DD'))
  )
  AND (A.DAILY_FEE * (1 - C.DISCOUNT_RATE / 100) * 30) >= 500000
  AND (A.DAILY_FEE * (1 - C.DISCOUNT_RATE / 100) * 30) < 2000000
ORDER BY 
  FEE DESC,
  A.CAR_TYPE ASC,
  A.CAR_ID DESC;
