SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE * ((100 - C.DISCOUNT_RATE) * 0.01) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
WHERE 1=1 
AND A.CAR_TYPE IN ('SUV', '세단')
AND A.CAR_TYPE = C.CAR_TYPE
AND A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 1=1
and TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221131' 
AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101'
)
AND C.DURATION_TYPE = '30일 이상'
AND FLOOR(A.DAILY_FEE * ((100 - C.DISCOUNT_RATE) * 0.01) * 30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC