SELECT FLAVOR
FROM(
SELECT flavor, SUM(total_order) AS TOTAL_ORDER
FROM (SELECT  FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF 
GROUP BY FLAVOR
UNION ALL
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR)
GROUP BY flavor
ORDER BY TOTAL_ORDER DESC
)
WHERE ROWNUM <= 3